services:
  ai-agent-test:
    image: ai-agent-network-model:${APP_VERSION}
    container_name: ai-agent-test
    env_file:
      - .env.test
    ports:
      - "8001:8000"
    restart: unless-stopped
