sonar.projectKey=Alsewedy_ai-agent-network-model
sonar.organization=alsewedy
sonar.host.url=https://sonarcloud.io

sonar.projectName=AI Network Domain Agent
sonar.sourceEncoding=UTF-8
sonar.python.version=3.12

sonar.sources=.
sonar.tests=tests

sonar.exclusions=tests/*,.venv/,.sonar/,_pycache_/,.git/,.pytest_cache/,agent_design/*,rag/chunks.json
sonar.test.inclusions=tests/*/.py
